- README.md
- proxysql-admin
- proxysql-admin.cnf
- proxysql_galera_checker
- proxysql_node_monitor
Added the --include-slaves option to proxysql-admin. This option allows slave node to be automatically added to ProxySQL and will be monitored for status. The slave nodes will be used as an emergency fallback if all the XtraDB cluster nodes are in a state other than ONLINE.
- A slave node will be considered online as long as slave health is good (slave sql running) and it's behind no more than 3600 seconds according to the 'Seconds_Behind_Master' stat.
- A slave that has fallen behind more than 3600 seconds will be put into an 'OFFLINE_SOFT' state until it catches up.
- When the last available XtraDB Cluster node goes into a non-online state, the first available and 'ONLINE' slave node will be made active in the write hostgroup.
If no ONLINE slaves are found, any slave will be randomly …
> Adding --include-slaves and improving --write-node

- proxysql_node_monitor
+ Added automatically determined connection timeout to proxysql_node_monitor so a (PXC) node that is down is detected within check interval of monitor. Using the default timeout could cause proxysql_node_monitor to be still running when a new one is started by proxysql, hence ignoring it's results.
+ Deleted unused variables that were initialized with CLUSTER_HOST_INFO that just has been determined to be empty.
> Fixed proxysql_node_monitor missing host down when MySQL connection timeout exceeds check interval of ProxySQL.

- tests/proxysql-admin-testsuite.bats
This is doing following:
- checking that mysql_servers and runtime_mysql_servers tables are equal
- stopping initial writer node
- checking that tables are updated
- starting the stopped node again
- checking that tables are updated
Test run:
```
ubuntu@ubuntu-test:~$ ./proxysql-admin-tool/tests/proxysql-admin-testsuite.sh /home/ubuntu/workdir
Started PXC node1. Socket : /home/ubuntu/workdir//Percona-XtraDB-Cluster-5.7.20-rel18-29.24.1.Linux.x86_64.ssl100/node1/socket.sock
Started PXC node2. Socket : /home/ubuntu/workdir//Percona-XtraDB-Cluster-5.7.20-rel18-29.24.1.Linux.x86_64.ssl100/node2/socket.sock
Started PXC node3. Socket : /home/ubuntu/workdir//Percona-XtraDB-Cluster-5.7.20-rel18-29.24.1.Linux.x86_64.ssl100/node3/socket.sock
proxysql-admin generic bats test log
✓ run proxysql-admin …
```
> PQA-156 - Add test for updating runtime_mysql_servers table

- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
Now, proxysql-admin can configure multiple clusters in proxysql.
Pre-requisites to configure multiple clusters in proxysql.
- Cluster name (wsrep_cluster_name) should be unique.
- proxysql-admin.cnf configuration differences
- ProxySQL READ/WRITE hostgroup should be different for each cluster.
- Application user should be different for each cluster.
PS : Host priority feature support only one cluster at a time.
> Updated proxysql-admin script to configure multiple clusters in proxysql

- tests/generic-test.bats
- tests/proxysql-admin-testsuite.bats
- tests/proxysql-admin-testsuite.sh
```
proxysql-admin generic bats test log
✓ run proxysql-admin under root privileges
✓ run proxysql-admin without any arguments
✓ run proxysql-admin --help
✓ run proxysql-admin with wrong option
✓ run proxysql-admin --config-file without parameters
✓ run proxysql-admin check default configuration file
✓ run proxysql-admin --proxysql-username without parameters
✓ run proxysql-admin --proxysql-port without parameters
✓ run proxysql-admin --proxysql-hostname without parameters
✓ run proxysql-admin --cluster-username without parameters
✓ run proxysql-admin --cluster-port without parameters
✓ run proxysql-admin --cluster-hostname without parameters
✓ run proxysql-admin --cluster-app-username without parameters
✓ run proxysql-admin --monitor-username without parameters
✓ run proxysql-admin …
```
> PQA-234 : Add more testcases in proxysql-admin test-suite

- proxysql-admin
This commit puts quotes around the MONITOR_USERNAME environment variable
to be consistent with the others. We ran into a bug where a dash in the
hostname was causing the monitoring user to have a dash in it, and mysql
complained that:
> mysql> create user monitor_ubuntu-xenial-yul-314584@'%' IDENTIFIED BY 'abc';
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-xenial-yul-314584@'%' IDENTIFIED BY 'abc'' at line 1
> Propertly quote MONITOR_USERNAME in admin script query

- README.md
- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
Fixed PSQLADM-2 : proxysql_galera_checker doesn't check if another instance of itself is already running
Fixed PSQLADM-39 : proxysql_node_monitor login error message is misleading.
Fixed PSQLADM-40 : ProxySQL scheduler generates many proxysql_(galera_checker|node_monitor) processes with wrong proxysql credentials
Fixed PSQLADM-41: Improve timeout error handing
Fixed PSQLADM-42 : Inconsistent date format in ProxySQL and scripts.
> V1.4.7 dev

- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
- Fixed PSQLADM-45 : config-file option requires an argument but that's not visible from help screen.
- Fixed PSQLADM-48 : ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode file will be missing with ProxySQL-admin upgrade (1.4.5 or before to 1.4.6 onwards).
- Fixed PSQLADM-52 : The proxysql_galera_checker script is not checking empty query rules.
- Fixed PSQLADM-54 : proxysql_node_monitor is not changing OFFLINE_HARD status properly when the node comes back online.
> V1.4.8 dev

- proxysql-status
This change includes the dump of /var/lib/proxysql/host_priority.conf and /etc/proxysql-admin.cnf
Output was changed, now it forces tabular format.
> Dump host_priority / proxysql-admin.cnf  and changed output format

- proxysql-admin
In function `syncusers` is problem with already existing users in proxySQL which have new password.
All users with new password are deleted from ProxySQL and added with new password into ProxySQL but they are again removed in second test because they don't have new password in `$proxysql_users`.
> Fixed bug that proxysql users are not ckecked again in syncusers

- proxysql-admin
This will avoid human interaction when deploying multiple proxysql's on the same cluster
> added option --without-check-monitor-user

- proxysql-admin
Fix for https://jira.percona.com/browse/PSQLADM-56
> syncuser uses hardcoded hostgroup . Fixes #PSQLADM-56

- README.md
- proxysql-admin
- proxysql-admin.cnf
- proxysql_node_monitor
This PR adds support for host priority while handling multiple clusters within the same ProxySQL.
It takes into consideration old file name (present on /etc/proxysql-admin.cnf) to avoid breaking the functionality when a user upgrades from a previous version of proxysql-admin
> PSQLADM-63

- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
@rameshvs02  Adjusted the scripts to accept everything on scheduler arg1.
- We need to make sure that we always pass `--config-file` as the first parameter. For example, if we have config file configured with `WRITE_HOSTGROUP=10` but we call `proxysql-admin --write-hostgroup=15`, we will end up having 15 on scheduler table. If we call `proxysql_node_monitor --write-hostgroup=15 --config-file=xxx` or `proxysql_galera_checker --write-hostgroup=15 --config-file=xxx` both will end up using 10 (config file value) instead of 15.
- Adjusted `proxysql_galera_checker` script to reshuffle arguments as ProxySQL  will pass everything as `argv[1] / $1`
TODO: We should port `mode` and `host_priority` to be passed as an argument instead of a physical file.
> Psqladm 31

- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
This PR will allow us to handle multiple proxysql instances through `proxysql-admin` on the same box. 
The Galera monitor scripts will check PXC node status using respective `proxysql-admin` configuration files. We can pass these configuration files with `proxysql-admin` enable command and this info will be saved in scheduler table for Galera monitoring scripts reference. 
```
proxysql-admin --enable --config-file=/etc/proxysql-admin_6032.cnf
proxysql-admin --enable --config-file=/etc/proxysql-admin_6132.cnf 
```
With this change, `proxysql-admin` tool will add mode and host priority info in `scheduler` table and  we can get rid of physical files like `<cluster_name>_mode` and `<cluster_name>_host_priority`. 
Scheduler table entry in proxysql database.
```
ProxySQL Instance 1
mysql> …
```
> PSQLADM-31 : Handle multiple proxysql instances in proxysql-admin

- proxysql_node_monitor
If we do not have any write node in `singlewrite` mode, this will PR will promote one of the read nodes to write node
> PSQLADM-67 : With singlewrite mode, Galera checker is not changing writer hostgroup id when nodes become ONLINE from OFFLINE_SOFT

- proxysql-admin
- proxysql_galera_checker
- tests/proxysql-admin-testsuite.sh
Issue
If the mode was not set on the command-line, this variable was used
without being set (thus the error)
Solution
Initialize the variable P_MODE to ""
Also fixed the help text to remove the notice that the mode has a
default value of 'singlewrite'.  This is incorrect as we try to look
for the mode file and will also check the mysql_servers entries to see
if the mode is 'singlewrite' or 'loadbal'
> PSQLADM-112 : proxysql_galera_checker: line 1978 P_MODE unbound variable

- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
- tests/async-slave-testsuite.bats
- tests/desynced-host-testsuite.bats
- tests/host-priority-testsuite.bats
- tests/proxysql-admin-testsuite.bats
- tests/proxysql-admin-testsuite.sh
- tests/test-common.bash
- tests/writer-is-reader-testsuite.bats
Issue
Scripts are not compatible with IPv6 formatted addresses.
The major problem is that we parse the IP addr and port
by breaking on the ':', which is a problem for IPv6 addresses
since they include ':' in the address.
Solution
Fixup the places where we use addresses.
Also add an "--ipv6" option to the test scripts.
> PSQLADM-68 : Make scripts IPv6 compatible

- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
Issue
We were querying for the max interval but got multiple rows back.
I was originally using DISTINCT to separate the intervals, but should
also do a MAX also.
Solution
Use MAX instead to get a single value back.
Also, added --debug to the usage()
> PSQLADM-116 : Scheduler is reloading servers on every run

- tests/proxysql-admin-testsuite.sh
Issue
When running the tests under sudo, the user needs to be set in the my.cnf
Solution
Set the my.cnf user to the user running the test script
> PSQLADM-104 : proxysql-admin testsuite bug fixes.

- proxysql-admin
Issue
This is a regression. --syncusers is not run when --enable is also set.
Solution
Allow --syncusers when --enable is set.
> PSQLADM-117 : --syncusers doesn't work when enabling cluster

- proxysql-admin
- tests/proxysql-admin-testsuite.sh
Issue
When working with a proxysql instance wiht no entries in the mysql_users,
an error would be reported (since we weren't getting any values back
from proxysql).
Note that the syncusers would still function correctly.
Solution
Move the check of the return value to the query (the query will succeed
but return no data).  The error occurs in the pipeline processing of
the query result.
> PSQLADM-126 : Script is showing an error when --syncusers is invoked

- proxysql_galera_checker
Issue
The ERR_FILE defaults to /dev/null, which means that errors that
occur before the ERR_FILE is set are lost (specifically this
means that a bad config file option will be lost)
Solution
Set the ERR_FILE to default to /dev/stderr, so that errors
will be dispalyed in proxysql.log
> PSQLADM-124 : Default ERR_FILE should not be /dev/null

- proxysql-admin
- proxysql_galera_checker
- proxysql_node_monitor
- tests/generic-test.bats
Issue
The options passed in via --write-node are not being validated.
Addresses without ports can be passed in, and then the script will
fail later.
Solution
Verify that a port is specified whenever a node address is passed
in via --write-node.
> PSQLADM-53 : proxysql-admin verification on --write-node

- proxysql-admin
Issue:
Mariadb 10.3 is currently not supported for syncusers command.
Sollution:
Checked the password field in mariadb 10.3 and added it to the version check in the syncusers function.
> syncusers mariadb 10.3 support
